### ISSUE TITLE
Підтримка системних команд

### ISSUE THREAD

**Issue by vovche** [statyan/gnome-extension-transcode-searchapp#15]
Актуальна версія на gnome 45 (ubuntu 23.10).
Коли екстеншн включений, то не знаходить системні команди типу poweroff restart (вимкнути перезапустити)

**Comment by andrijzyn** [comment]
Виправив, чекаємо поки автор заль'є мій пул реквест 🫶

**Comment by statyan** [comment]
Зроблено, дякую за підтримку! Якось провтикав ішшую створену ще в квітні, перепрошую
